<a href="https://colab.research.google.com/github/jsnunki/bluegenes-tissue-expression-visualizer/blob/master/python_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Welcome to Python for Data Science: Fundamentals! by Dataquest

In this course, we’ll learn the fundamentals of data science and Python programming. We'll then use this knowledge to analyze data about thousands of Android and Google Play mobile apps. We’ve designed this course for beginners — no previous math, stats, or programming experience required — so you can start learning right away.

At the end of the course, you’ll have a portfolio-worthy project to share with potential employers, and a certificate of completion to add to your LinkedIn profile.

In this course, we’ll focus primarily on Python programming for data science. In later courses, we'll build on this programming knowledge to learn data visualization, statistics, linear algebra, machine learning, databases, and more. All these courses fit together in a well-organized curriculum, so you don't have to get to the end of a course and worry about what to do next.

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_curriculum_new.gif)

There's been a lot of discussion and enthusiasm around data science in the last couple of years. Using data science, people have been able to build some amazing technologies:

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_achievments.png
)

To build data science technologies, we need to give the computer the proper instructions to learn from data. When we give instructions to a computer, we say that we're programming it.

To program a computer, we need to write the instructions in a special language, which we call a programming language. In this course, we'll learn Python, a programming language that offers great support for data science.

We'll start by instructing the computer to add two numbers together: 23 + 7. To do that, we need to:

In [ ]:
23+7


30

Above, we see the computer followed our instruction, and it returned 30 as a result.

Let's now do a quick exercise and give the computer a different instruction. The details of the exercise are below this paragraph.

Instruct the computer to calculate 8 + 42.


In [ ]:
8+42

50

However, we can ask the computer to perform more than just one calculation.

In the diagram below, we instruct the computer to perform three calculations (the diagram below illustrates the code editor you see on the right of the screen):


In [ ]:
23+7
10-6
12+38

50

The computer returned only 50 as a result, and it may look like it only performed the last addition, 12 + 38.

In reality, the computer performed all three calculations, but it only displayed the result for the last one. To display all three results, we need to use the print() command, like this:

In [ ]:
print(23+7)
print(10-6)
print(12+38)

30
4
50


Now let's practice using the print() command.
Using the print() command, display the result for:



*   40 + 4
*   200 - 25
*   14 + 3







In [ ]:
print(40+4)
print(200-25)
print(14+3)

44
175
17


Previously, we sent the computer three instructions and wrote each on a separate line. If we were to put them all on the same line, we'd get an error:

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_cb3_extra1.svg)

print(23 + 7) print(10 - 6) print(12 + 38) resulted in red text describing a syntax error. This is because all programming languages — Python included — have syntax rules. Each line of instructions has to comply with these rules.

This is similar to the syntax rules we have in human languages. If you want to use English to tell a friend that you like data science, you need to respect syntax rules to correctly convey your message. Your friend will understand "I like data science," but not "science I data like." Similarly, the computer didn't understand print(23 + 7) print(10 - 6) print(12 + 38) because the syntax was incorrect.

Running into errors is common when we're programming, and we'll constantly learn about errors and how to fix them. Now let's practice giving the computer more instructions.





In [ ]:
print(30 + 10 + 40)
print(4)
print(-3)

80
4
-3


All these instructions are collectively known as code. And each line of instruction is known as a line of code.

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_code_line_2.svg)

When we write code, we program the computer to do something. For this reason, we also call the code we write a computer program, or a program. The program we wrote in the previous exercise had three lines of code, but a program can be as small as one line.

The code we write serves as input to the computer. The result of executing the code is called output.

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_io.svg)

As we've learned, we can display the output using the print() command. Note, however, that the code editor displays the output of the last line of code regardless of whether we use print() or not. In the example below, we see the output of 2 + 3 is only displayed when 2 + 3 is the last line of code.

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_cb_extra1.svg)

Now let's get a little more practice with writing code. On the next screen, we'll learn about code comments.

In [ ]:
print(34+16)
print(34)
print(-34)

50
34
-34


The computer executes code from the first line downwards and ignores blank lines.
![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_cb_fb3.svg)

Besides blank lines, the computer also ignores any sequence of characters that comes to the right of the # symbol. In the example below, we use # before print(5 + 1), and we see the output of print(5 + 1) is not displayed anymore — this is because print(5 + 1) is not executed when it's preceded by #.

The sequence of characters that follows the # symbol is called a code comment. We can also use code comments to add information about our code and another way we could use code comments is adding a general description at the beginning of our program.




In [ ]:
# Test program
# beforeprint(5 + 1)
print(5+1)
print(8-7) #This is the line that outputs 1

6


Now let's get a little practice with code comments.
In the code editor on the right,  We need to add three lines of code and used this # symbol:



In [ ]:
# INITIAL CODE
print(34 + 16)
print(34)
print(-34)

50
34
-34


Previously, we wrote programs that only performed additions and subtractions. We can also perform multiplication and division in Python. To perform multiplication, we need to use the * character. For instance, this is how we multiply 3 by 2:



In [ ]:
3*2


6

To perform division, we use the / character. This is how we divide 3 by 2:



In [ ]:
3/2

1.5

We can also perform exponentiation (raising a number to a power) by using **. For example, this is how we can raise 4 to the power of 2 (in mathematical notation, we'd write this as ).


In [ ]:
4**2

16

The arithmetical operations we do in Python follow the usual order of operations we know from mathematics. Parentheses are calculated first, then exponentiation, then division and multiplication, and finally, addition and subtraction.

In [ ]:
print(4+2*10)
print((4+2)*10)

24
60


Looking at the code example above, we can deduce from the first operation (4 + 2 * 10) and its corresponding result (24) that multiplication precedes addition. However, for the second operation ((4 + 2) * 10), the addition is calculated first because this time it's surrounded by parentheses. Consequently, the result is 60.

So far we've used space characters between numbers and operators (+, -, *, /, ** are operators). For instance, we've used 4 + 5 instead of 4+5. But Python's syntax rules do not enforce this, so both 4 + 5 and 4+5 will run correctly. However, we encourage you to use spaces in your own code as this helps with readability.

In [ ]:
print(16*10)
print(48/5)
print(5**3)

160
9.6
125


At Dataquest, each course is composed of missions, and this screen marks the end of the first mission. Congratulations!

So far, we've focused on learning how to successfully run simple computer programs in Python. In the next mission, we'll use this fundamental knowledge to learn more about programming and data science:

We'll learn how to save our data using variables.
We'll learn how to work better with numerical data.
We'll learn how to work with text data.

Let's say we want to save the result of an arithmetical operation for later work. For instance, (8 + 2) * 2 equals 20, and we want to save 20. This is the code we need to run to save 20. If we print the name result, the output is 20:





In [ ]:
result = 20
print(result)

20


We can also save directly (8 + 2) * 2 instead of saving 20.
Notice, however, that print(result) outputs 20, not (8 + 2) * 2. This is because the computer first calculates (8 + 2) * 2 and then saves the result 20 to result.


In [ ]:
result=(8 + 2) * 2 
print(result)



20


In [ ]:
#Now let's do a quick exercise and resume this discussion in the next screen.
result = ((42 - 11) * 22)
print(result)

682


When we run the code result = 20, the value 20 is saved in the computer memory. The computer memory has many storage locations, and 20 is saved to one particular location.

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_memory.svg)

The storage location to which we saved 20 has a unique identifier, and we can use it to access 20. The identifier is named result, and we named it that way when we ran the code result = 20. We can use the identifier result to access 20 in other lines of code:

In [ ]:
result = 20
print(result)
print(result+10)

20
30


The storage location for 20 is more commonly known as a variable. When we ran the code result = 20, we stored 20 in a variable (storage location) named result — so result is a variable name.

Note that we need to write the variable name to the left of the = operator and the value we want to store to the right. So if we want to store the value 20 to a variable named result, we must write result = 20, not 20 = result.

We chose the name result arbitrarily, but we could have chosen something different:



In [ ]:
another_name = 20
print(another_name)
print(another_name + 10)

20
30


Now let's get more practice with variables.



In [ ]:
a_value = 15
a_result = (25 - 7) * 17
print(a_value)
print(a_result+12)
print(a_value + a_result)

15
318
321


In the last screen, we learned that we can choose different names for variables. However, the names we can use must comply with a number of syntax rules. For instance, naming a variable a result will output a syntax error because we're not allowed to use space characters in variable names.

In [ ]:
a result = 20

SyntaxError: ignored

These are the two syntax rules we need to be aware of when we're naming variables:

We must use only letters, numbers, or underscores (we can't use apostrophes, hyphens, whitespace characters, etc.).
Variable names cannot start with a number.

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_variable_naming.svg)

Note that variable names are case sensitive, which means that a variable named result is different than a variable named Result:

In [ ]:
result = 20
Result = 30
print(result)
print(Result)

20
30


The value stored in a variable can be updated. Below, we first store 30 in the variable x, and then we update x to store 70 instead.

In [ ]:
x = 70
print(x)

x = 30
print(x)

70
30


We can also update a variable by doing arithmetical operations:



In [ ]:
x = 30
print(x)
print(x + 70)

x = x + 70
print(x)


30
100
100


Notice in the code above that:

The variable x initially stores a value of 30.
x + 70 evaluates to 100 because x stores a value of 30 — so x + 70 becomes 30 + 70.
When we run x = x + 70, x is updated to store the result of x + 70, which is 100. Running x = x + 70 is the same as running x = 30 + 70 because x stores 30.
print(x) outputs 100 after we run x = x + 70.

There are several syntax shortcuts we can use to update a variable when we're doing arithmetical operations. In the code above, for instance, we can write x += 70 instead of x = x + 70:

In [ ]:
x = 30
x += 70
print(x)

100


Below is a table with some syntax shortcuts we can use:


![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_update.svg)

Notice that these operators (+=, -=, *=, /=, **=) can only be used to update a variable. This means the variable being updated must already store a value. In other words, the variable must already be defined. When we try to update a variable that we haven't defined, we get an error called NameError.

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_cb17.svg)

This kind of error is different from the syntax error we learned about in the first mission. y += 10 is correct Python syntax, but the computer returns an error because it can't update a variable that hasn't been yet defined. Whenever the syntax is correct but the computer still returns an error for one reason or another, it's called a runtime error.

Notice also that we updated a variable using x = x + 1. In mathematics, x = x + 1 would be a false statement because x can never be equal to x + 1. This tells us that the = operator doesn't have the same meaning as it does in mathematics.

In Python, the = operator tells us that the value on the right is assigned to the variable on the left. It doesn't tell us anything about equality. We call = an assignment operator, and we read code like x = 5 as "five is assigned to x" or "x is assigned five," but not "x equals five."

In [ ]:
variable_1 = 20
variable_2 = 20

variable_2 += 10
variable_1 *= 4
print(variable_1)
print(variable_2)

80
30


So far, we only worked with [integers](https://www.mathsisfun.com/definitions/integer.html) like 20, -3, 30, etc. We can also make computations with decimal numbers:


In [ ]:
print(8.4 + 1.5)
print(-0.2 + 1.3)

9.9
1.1


In mathematics, integers are not the same as decimal numbers, and Python acknowledges this difference. We can use the type() command to see the type of a value, and confirm that Python distinguishes between integers and decimal numbers:

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_cb19.svg)

Notice that the integer 2 has the int type, and the decimal number 8.5 has the float type. All integers have the int type, and all decimal numbers have the float type.

In computer programming, values are classified into different types, or data types. The type of value offers the computer the required information about the way that value should be handled. Depending on the type, the computer will know how to store a value in memory, or what operations can and can't be performed on a value.

int and float values have different types, but we can mix the values together in arithmetical operations. So we're not limited, for instance, to add an int value only to another int value — we can add an int value to a float value:

In [ ]:
print(3 + 2.5)
print(2.5 * 4)

5.5
10.0


In [ ]:
variable_1 = 10
variable_2 = 2.5

variable_1 += 6.5
variable_2 *= 2

print(variable_1)
print(variable_2)

16.5
5.0


It's possible to convert a float to an integer and vice versa. To convert an integer to a float, we can use the float() command. To convert a float to an integer, we can use the int() command:

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_cb21.svg)

Notice the int() command rounded 4.3 down to 4. int() will always round a float down, even if the number after the decimal point is greater than five.



In [ ]:
int(4.99)

4

If we want to round off a number, we can instead use the round() command, which has more flexibility and can also round up:
![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_cb23.svg)

Note that it's possible to combine commands. For instance, we can encompass a round() command within a print() command. This is useful in some cases — if we wrote three round() commands one after another, only the output of the last one would be displayed:

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_cb24.svg)

Note that running the round() command doesn't change the value stored by a variable unless we assign the rounded value back to the variable:

In [ ]:
a_value = 3.7
print(round(a_value))
print(a_value)

a_value = (round(a_value))
print(a_value)

4
3.7
4


In [ ]:
variable_a = 13.9
variable_b = 2.8

variable_a = round(variable_a)
variable_b = int(variable_b)
print(variable_a)
print(variable_b)

14
2


So far, we've only dealt with int and float values. But in data science, numbers are not the only type of data we work with. For instance, consider the table below, which provides some information about five mobile applications from the iOS store:

Data source:[Mobile App Store data set (Ramanathan Perumal)](https://www.kaggle.com/ramamet4/app-store-apple-data-set-10k-apps)

[Tabla de datos](https://drive.google.com/file/d/1Knz47r7mVqHgaJ2Hu7DJ2dlW4q1i4Vfi/view?usp=sharing)



In [ ]:
import pandas as pd
df = pd.read_csv("https://docs.google.com/spreadsheets/d/17b-4W9nUqh0QeNDLfGPFXhlKvCru46MXFIx46Jyebfo/export?format=csv&gid=0")
df.head()


Unnamed: 0         id  ... lang.num  vpp_lic
0           1  281656475  ...       10        1
1           2  281796108  ...       23        1
2           3  281940292  ...        3        1
3           4  282614216  ...        9        1
4           5  282935706  ...       45        1

[5 rows x 17 columns]

We can see the data in columns track_name and currency are represented using text, not numbers. In Python, we can create text by enclosing a sequence of characters within quotation marks (" "):


In [ ]:
app_name = "Facebook"
currency = "USD"
print(app_name)

Facebook


In [ ]:
import pandas as pd
appdata_df = pd.read_csv("https://docs.google.com/spreadsheets/d/17b-4W9nUqh0QeNDLfGPFXhlKvCru46MXFIx46Jyebfo/export?format=csv&gid=0")
print(appdata_df)

      Unnamed: 0          id  ... lang.num  vpp_lic
0              1   281656475  ...       10        1
1              2   281796108  ...       23        1
2              3   281940292  ...        3        1
3              4   282614216  ...        9        1
4              5   282935706  ...       45        1
...          ...         ...  ...      ...      ...
7192       11081  1187617475  ...        1        1
7193       11082  1187682390  ...        1        1
7194       11087  1187779532  ...        1        1
7195       11089  1187838770  ...        2        1
7196       11097  1188375727  ...        2        1

[7197 rows x 17 columns]


In [ ]:
appdata_df.head() #I need more information about this ¿How working?

Unnamed: 0         id  ... lang.num  vpp_lic
0           1  281656475  ...       10        1
1           2  281796108  ...       23        1
2           3  281940292  ...        3        1
3           4  282614216  ...        9        1
4           5  282935706  ...       45        1

[5 rows x 17 columns]

In [ ]:
table_1=appdata_df[['track_name', 'price', 'currency', 'rating_count_tot', 'user_rating']]
table_1.head()

track_name  ...  user_rating
0                                    PAC-MAN Premium  ...          4.0
1                          Evernote - stay organized  ...          4.0
2    WeatherBug - Local Weather, Radar, Maps, Alerts  ...          3.5
3  eBay: Best App to Buy, Sell, Save! Online Shop...  ...          4.0
4                                              Bible  ...          4.5

[5 rows x 5 columns]

In [ ]:
table_2 = table_1.iloc[[16, 519, 1346, 707, 7 ]]
table_2.head()

track_name  price currency  rating_count_tot  user_rating
16                   Facebook    0.0      USD           2974676          3.5
519                 Instagram    0.0      USD           2161558          4.5
1346           Clash of Clans    0.0      USD           2130805          4.5
707                Temple Run    0.0      USD           1724546          4.5
7     Pandora - Music & Radio    0.0      USD           1126879          4.0

We can see the data in columns track_name and currency are represented using text, not numbers. In Python, we can create text by enclosing a sequence of characters within quotation marks (" "):

In [ ]:
app_name = "Facebook"
currency = "USD"
print(app_name)
print(currency)

Facebook
USD


Python syntax allows both double quotation marks (" ") and single quotation marks (' '). So if we want to create the word "Facebook," we can use either "Facebook", or 'Facebook'.

In [ ]:
fb_1 = "Facebook"
fb_2 = 'Facebook'

print(fb_1)
print(fb_2)

Facebook
Facebook


In programming, we call sequences of characters like "Facebook", "USD", or "dasdaslkj" strings. In Python, a string is of the str type:



In [ ]:
type('Facebook')

str

When we create strings, we're not limited to using letters — we can also use numbers, spaces, or other characters:



In [ ]:
game = 'Clash of Clans'
short_description = 'Clash of clans is free and has an average rating of 4.5'
print(game)
print(short_description)

Clash of Clans
Clash of clans is free and has an average rating of 4.5


In [ ]:
app_name = "Pandora - Music & Radio"

average_rating = "4.0"

total_ratings = "1724546"

price = "free"

print(app_name)
print(average_rating)
print(total_ratings)
print(price)

Pandora - Music & Radio
4.0
1724546
free


Sometimes we'll need to create strings with quotation marks inside, like in this example: Facebook's old motto was 'move fast and break things'.

In situations like these, we need to alternate double quotation marks (" ") with single quotation marks (' '):

In [ ]:
motto = "Facebook's old motto was 'move fast and break things'."
print(motto)

Facebook's old motto was 'move fast and break things'.


Above, we started the string with a double quotation mark. This lets Python know the string ends where the second double quotation mark is. As a consequence, Python considers the single quotation marks in 'move fast and break things' as being part of the string.

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_cb31.svg)

However, we may want to surround the motto move fast and break things with double quotation marks: Facebook's old motto was "move fast and break things.". One solution is using single quotation marks to specify the start and the end of the string. However, the single quotation mark in Facebook's will cause Python to think that the string ends there.

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_cb32.svg)

Creating the string above will result in a syntax error because Python is confused about what comes after the string.





In [ ]:
motto = 'Facebook's old motto was "move fast and break things"

SyntaxError: ignored

Fortunately, we can cancel the special function of the second single quotation mark (its special function is to end the string) by typing a backslash character (\) in front of it:



In [ ]:
motto = 'Facebook\'s new motto is "move fast with stable infra."'

print(motto)

Facebook's new motto is "move fast with stable infra."


![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_cb34.svg)

The \ character has a special function within a string: it escapes (cancels) the special function of characters. Above, we used \ to escape the second single quotation mark, which had the special function of ending the string.

When we have two or more distinct strings, it's possible to link them together using the + operator:

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_cb35.svg)

The process of linking two or more strings together is called concatenation.

It's also possible to concatenate a string with one or more copies of itself using the * operator, followed by a number which specifies the number of times the string has to be multiplied:

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_cb36.svg)

We can't perform arithmetical operations between strings and integers, or strings and floats (decimal numbers).

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_cb37.svg)

The only exception is when we concatenate a string with copies of itself and use code like 'a' * 2. But that's not an arithmetical operation anyway, so this exception is rather syntactical.

If the strings contain characters that form a valid number (like '4', '3.3', '12', etc.), it's possible to convert them to integers or floats first, and then do the arithmetical operations. We can use the int() or float() command to convert a string of type str to a number of type int or float.

Note that we can also convert an int or a float to a str using the str() command. Below, we convert the integer 4 to the string '4' (notice the quotation marks in '4').



In [ ]:
str(4)

'4'

On a side note, strings are displayed without quotation marks when we use the print() command.

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_noquotes.svg)

So far, we've only been working with one-line strings, but we can also write strings over many lines using the triple quotation mark symbol (''' or """).

![alt text](https://s3.amazonaws.com/dq-content/311/py1m1_cb40.svg)

Using triple quotation marks also allows us to use both single and double quotation marks without needing to escape them.



In [ ]:
motto = '''Facebook\'s new motto is "move fast with stable infra".'''

print(motto)

Facebook's new motto is "move fast with stable infra".




1.   Assign the string Facebook's rating is to a variable named facebook.
2.   Assign the float 3.5 to a variable named fb_rating.
3.   Assign the float 3.5 to a variable named fb_rating.
4.   Convert fb_rating from a float to a string using the str() command, and assign the converted value to a new variable named fb_rating_str.
5.  Concatenate the strings stored in facebook and fb_rating_str to form the string Facebook's rating is 3.5.
Assign the concatenated string to a variable named fb.
6. You'll need to add a space character between Facebook's rating is and 3.5 to avoid ending up with the string Facebook's rating is3.5.
7. Display the fb variable using print() — this is required for answer checking.











In [ ]:
facebook = "Facebook's rating is "
fb_rating = 3.5

fb_rating_str = str(fb_rating)

fb = (facebook+fb_rating_str)

print (fb)

Facebook's rating is 3.5


We worked with this table:

In [ ]:
import pandas as pd
appdata_df = pd.read_csv("https://docs.google.com/spreadsheets/d/17b-4W9nUqh0QeNDLfGPFXhlKvCru46MXFIx46Jyebfo/export?format=csv&gid=0")
table_1 = appdata_df[['track_name', 'price', 'currency', 'rating_count_tot', 'user_rating']]
table_2 = table_1.iloc[[16, 519, 1346, 707, 7 ]]
table_2.head()

track_name  price currency  rating_count_tot  user_rating
16                   Facebook    0.0      USD           2974676          3.5
519                 Instagram    0.0      USD           2161558          4.5
1346           Clash of Clans    0.0      USD           2130805          4.5
707                Temple Run    0.0      USD           1724546          4.5
7     Pandora - Music & Radio    0.0      USD           1126879          4.0

Each value in the table is a data point. For instance, the first row has five data points:

* Facebook
* 0.0
* USD
* 2974676
* 3.5

A collection of data points make up a data set. We can understand our entire table above as a collection of data points, so we call the entire table a data set. We can see that our data set has five rows and five columns.

When we work with data sets, we need to store them in the computer memory to be able to retrieve and manipulate the data points. Using what we've learned so far, we might think we could store each data point in a variable — for instance, this is how we might store the first row's data points:



In [ ]:
track_name_row1 = 'Facebook'
price_row1 = 0.0
currency_row1 = 'USD'
rating_count_tot_row1 = 2974676
user_rating_row1 = 3.5

Above, we stored:

* The text "Facebook" as a string
* The price 0.0 as a float
* The text "USD" as a string
* The rating count 2,974,676 as an integer
* The user rating 3.5 as a float

Creating a variable for each data point in our data set would be a cumbersome process. Fortunately, we can store data more efficiently using lists. This is how we can create a list of data points for the first row:



In [ ]:
row_1 = ['Facebook', 0.0, 'USD', 2974676, 3.5]
print(row_1)
type(row_1)

['Facebook', 0.0, 'USD', 2974676, 3.5]


list

To create the list above, we:

* Typed out a sequence of data points and separated each with a comma: 'Facebook', 0.0, 'USD', 2974676, 3.5
* Surrounded the sequence with brackets: ['Facebook', 0.0, 'USD', 2974676, 3.5]
After we created the list, we stored it in the computer's memory by assigning it to a variable named row_1.

To create a list of data points, we only need to:

* Separate the data points with a comma.
* Surround the sequence of data points with brackets.
* Now let's get a little practice with creating lists.

In [ ]:
row_2 = ["Instagram", 0.0, "USD", 2161558, 4.5]

row_3 = ["Clash of Clans", 0.0, "USD", 2130805, 4.5]

A list can contain both mixed and identical data types (so far we've learned four data types: integers, floats, strings, and lists). A list like [4, 5, 6] has identical data types (only integers), while the list ['Facebook', 0.0, 'USD', 2974676, 3.5] has mixed data types:

* Two strings ('Facebook', 'USD')
* Two floats (0.0, 3.5)
* One integer (2974676)

The ['Facebook', 0.0, 'USD', 2974676, 3.5] list has five data points. To find the length of a list, we can use the len() command:

In [ ]:
print(row_1)
print(len(row_1))

list_1 = [1, 5, 0]
print(len(list_1))

list_2 = []
print(len(list_2))

['Facebook', 0.0, 'USD', 2974676, 3.5]
5
3
0


For small lists, we can just count the data points on our screens to find the length, but the len() command will prove very useful later on, when we work with lists containing thousands of elements (we'll see an actual example later in this mission).

Each element (data point) in a list has a specific number associated with it, called an index number. The indexing always starts at 0, so the first element will have the index number 0, the second element the index number 1, and so on.

![alt text](https://s3.amazonaws.com/dq-content/312/py1m2_positive_idx.svg)

To quickly find the index of a list element, identify its position number in the list, and then subtract 1. For example, the string 'USD' is the third element of the list (position number 3), so its index number must be 2 since 3 - 1 = 2.

The index numbers help us retrieve individual elements from a list. Looking back at the list row_1 from the code example above, we can retrieve the first element (the string 'Facebook') with the index number 0 by running the code row_1[0].

In [ ]:
print(row_1)
row_1[0]

['Facebook', 0.0, 'USD', 2974676, 3.5]


'Facebook'

As a side note, you may have noticed above that we used row_1[0] rather than print(row_1[0]). Recall from the first mission that the code editor displays the last line of code regardless of whether we use print() or not.

The syntax for retrieving individual list elements follows the model list_name[index_number]. For instance, the name of our list above is row_1 and the index number of the first element is 0 — following the list_name[index_number] model, we get row_1[0], where the index number 0 is in square brackets after the variable name row_1.

![alt text](https://s3.amazonaws.com/dq-content/312/py1m2_pattern.svg)

This is how we can retrieve each element in row_1:

![alt text](![alt text](https://s3.amazonaws.com/dq-content/312/py1m2_cb5.svg))

Retrieving list elements makes it easier to perform operations. For instance, we can select the ratings for Facebook and Instagram, and find the average or the difference between the two:

In [ ]:
print(row_1)
print(row_2)

difference = row_2[4] - row_1[4]
average_rating = (row_1[4] + row_2[4]) / 2

print(difference)
print(average_rating)

['Facebook', 0.0, 'USD', 2974676, 3.5]
['Instagram', 0.0, 'USD', 2161558, 4.5]
1.0
4.0


In the code editor, you can already see the lists for the first three rows.

The fourth element in each list describes the number of ratings an app has received. Retrieve this fourth element from each list, and then find the average value of the retrieved numbers.

1. Assign the fourth element from the list row_1 to a variable named ratings_1. Don't forget that the indexing starts at 0.
2. Assign the fourth element from the list row_2 to a variable named ratings_2.
3. Assign the fourth element from the list row_3 to a variable named ratings_3.
4. Add the three numbers retrieved together and save the sum to a variable named total.
5. Divide the sum (now saved in the variable total) by 3 to get the average number of ratings for the first three rows. Assign the result to a variable named average.

In [ ]:
row_1 = ['Facebook', 0.0, 'USD', 2974676, 3.5]
row_2 = ['Instagram', 0.0, 'USD', 2161558, 4.5]
row_3 = ['Clash of Clans', 0.0, 'USD', 2130805, 4.5]

ratings_1 = row_1[3]
ratings_2 = row_2[3]
ratings_3 = row_3[3]

total = (ratings_1+ratings_2+ratings_3)

average = total/3

print (ratings_1)
print (ratings_3)
print (ratings_3)
print(total)
print(average)

2974676
2130805
2130805
7267039
2422346.3333333335


In Python, we have two indexing systems for lists:

* Positive indexing: the first element has the index number 0, the second element has the index number 1, and so on.
* Negative indexing: the last element has the index number -1, the second to last element has the index number -2, and so on.

![alt text](https://s3.amazonaws.com/dq-content/312/py1m2_positive_negative.svg)

In practice, we almost always use positive indexing to retrieve list elements. Negative indexing is useful when we want to select the last element of a list — especially if the list is long, and we can't tell the length by counting.

In [ ]:
print(row_1)

print(row_1[-1])
print(row_1[4])

['Facebook', 0.0, 'USD', 2974676, 3.5]
3.5
3.5


Notice that if we use an index number that is outside the range of the two indexing systems, we'll get an IndexError.

![alt text](https://s3.amazonaws.com/dq-content/312/py1m2_cb8.svg)

The last element in each list shows the average rating of each application.

Retrieve the ratings for the first three rows, and then find the average value of all the ratings retrieved.

1. Assign the last element from the list row_1 to a variable named rating_1. Try to take advantage of negative indexing.
2. Assign the last element from the list row_2 to a variable named rating_2.
3. Assign the last element from the list row_3 to a variable named rating_3.
4. Add the three ratings together and save the sum to a variable named total_rating.
5. Divide the total by 3 to get the average rating. Assign the result to a variable named average_rating.

In [ ]:
row_1 = ['Facebook', 0.0, 'USD', 2974676, 3.5]
row_2 = ['Instagram', 0.0, 'USD', 2161558, 4.5]
row_3 = ['Clash of Clans', 0.0, 'USD', 2130805, 4.5]
rating_1 = row_1[-1]
rating_2 = row_2[-1]
rating_3 = row_3[-1]

total_rating = rating_1 + rating_2 + rating_3
average_rating = total_rating / 3

Oftentimes, we need to retrieve more than one element from a list. Let's say we have the list ['Facebook', 0.0, 'USD', 2974676, 3.5], and we're interested in isolating only the name of the app and the data about ratings (the number of ratings and the rating). This is how we can do that, using what we've learned so far:



In [ ]:
print(row_1)
app_name = row_1[0]
n_of_ratings = row_1[3]
rating = row_1[-1]
print(app_name)
print(n_of_ratings)
print(rating)

['Facebook', 0.0, 'USD', 2974676, 3.5]
Facebook
2974676
3.5


If we wanted to do this for every app, we'd end up having a lot of variables, making our code lengthy and hard to keep track of. A better solution is to store the data we want in a separate list.

In [ ]:
print(row_1)

fb_rating_data = [row_1[0], row_1[3], row_1[-1]]
print(fb_rating_data)

['Facebook', 0.0, 'USD', 2974676, 3.5]
['Facebook', 2974676, 3.5]


Above, we managed to isolate the three list elements of interest in a separate list. To do that, we used the code row_1[0], row_1[3], row_1[-1] to retrieve the first, fourth, and last element, and then we surrounded that part of code with square brackets to create a new list.

1. For Facebook, Instagram, and Pandora — Music & Radio, isolate the rating data in separate lists. Each list should contain the name of the app, the rating count, and the user rating. Don't forget that indexing starts at 0.

* For Facebook, assign the list to a variable named fb_rating_data.
* For Instagram, assign the list to a variable named insta_rating_data.
* For Pandora — Music & Radio, assign the list to a variable named pandora_rating_data.

2. Compute the average user rating for Facebook, Instagram, and Pandora — Music & Radio using the data you stored in fb_rating_data, insta_rating_data, and pandora_rating_data.

* You'll need to add the ratings together first, and then divide the total by the number of ratings.
* Assign the result to a variable named avg_rating.
* As a side note, we could calculate the average rating here a little bit better using the weighted mean — we'll learn about the weighted mean in the statistics courses.

In [ ]:
row_1 = ['Facebook', 0.0, 'USD', 2974676, 3.5]
row_2 = ['Instagram', 0.0, 'USD', 2161558, 4.5]
row_3 = ['Clash of Clans', 0.0, 'USD', 2130805, 4.5]
row_4 = ['Temple Run', 0.0, 'USD', 1724546, 4.5]
row_5 = ['Pandora - Music & Radio', 0.0, 'USD', 1126879, 4.0]

fb_rating_data = [row_1[0], row_1[3], row_1[-1]]
insta_rating_data = [row_2[0], row_2[3], row_2[4]]
pandora_rating_data = [row_5[0], row_5[3], row_5[4]]


print(fb_rating_data)
print(insta_rating_data)
print(pandora_rating_data)


avg_rating = (fb_rating_data[2] + insta_rating_data[2] + pandora_rating_data[2]) / 3
print(avg_rating)

['Facebook', 2974676, 3.5]
['Instagram', 2161558, 4.5]
['Pandora - Music & Radio', 1126879, 4.0]
4.0


In the last exercise, we retrieved the first, fourth, and last list elements to isolate the rating data. We can also retrieve the first three list elements to isolate the pricing data:


In [ ]:
print(row_3)

cc_pricing_data = [row_3[0], row_3[1], row_3[2]]
print(cc_pricing_data)

['Clash of Clans', 0.0, 'USD', 2130805, 4.5]
['Clash of Clans', 0.0, 'USD']


Instead of selecting element by element, we can use a syntax shortcut:

![alt text](https://s3.amazonaws.com/dq-content/312/py1m2_cb12.svg)

When we select the first n elements (n stands for a number) from a list named a_list, we can use the syntax shortcut a_list[0:n]. In the example above, we needed to select the first three elements from the list row_3, so we used row_3[0:3].

When we selected the first three elements, we sliced a part of the list. For this reason, the process of selecting a part of a list is called list slicing.

There are many ways that we might want to slice a list:

![alt text](https://s3.amazonaws.com/dq-content/312/py1m2_slices.svg)

To retrieve any list slice we want:

1. We first need to identify the first and the last element of the slice.
2. We then need to identify the index numbers of the first and the last element of the slice.
3. Finally we can retrieve the list slice we want by using the syntax a_list[m:n], where:
* m represents the index number of the first element of the slice; and
* n represents the index number of the last element of the slice plus one (if the last element has the index number 2, then n will be 3, if the last element has the index number 4, then n will be 5, and so on).

![alt text](https://s3.amazonaws.com/dq-content/312/py1m2_any_slice.svg)

When we need to select the first or last x elements (x stands for a number), we can use even simpler syntax shortcuts:

* a_list[:x] when we want to select the first x elements.
* a_list[-x:] when we want to select the last x elements.



In [2]:
row_3 = ['Clash of Clans', 0,0, 'USD', 2130805, 3.5]

firt_3 = row_3[:3]
last_3 = row_3[-3:]

print(firt_3)
print(last_3)

['Clash of Clans', 0, 0]
['USD', 2130805, 3.5]


1. Select the first four elements from row_1 using a list slicing syntax shortcut. Assign the output to a variable named first_4_fb.
2. Select the last three elements from row_1 using a list slicing syntax shortcut. Assign the output to a variable named last_3_fb.
3. From row_5, select the list slice ['USD', 1126879] using a list slicing syntax shortcut. Assign the output to a variable named pandora_3_4.

In [10]:
row_1 = ['Facebook', 0.0, 'USD', 2974676, 3.5]
row_2 = ['Instagram', 0.0, 'USD', 2161558, 4.5]
row_3 = ['Clash of Clans', 0.0, 'USD', 2130805, 4.5]
row_4 = ['Temple Run', 0.0, 'USD', 1724546, 4.5]
row_5 = ['Pandora - Music & Radio', 0.0, 'USD', 1126879, 4.0]


first_4_fb = row_1[:4]
last_3_fb = row_1[-3:]
pandora_3_4 = row_5[2:4]

print(first_4_fb)
print(last_3_fb)
print(pandora_3_4)

['Facebook', 0.0, 'USD', 2974676]
['USD', 2974676, 3.5]
['USD', 1126879]


Previously, we introduced lists as a better alternative to using one variable per data point. Instead of having a separate variable for each of the five data points 'Facebook', 0.0, 'USD', 2974676, 3.5, we can bundle the data points together into a list, and then store the list in a single variable.

So far, we've been working with a data set having five rows, and we've been storing each row as a list in a separate variable (the variables row_1, row_2, row_3, row_4, and row_5). If we had a data set with 5,000 rows, however, we'd end up with 5,000 variables, which will make our code messy and almost impossible to work with.

To solve this problem, we can store our five variables in a single list:

![alt text](https://s3.amazonaws.com/dq-content/312/py1m2_cb14.svg)

As we can see, data_set is a list that stores five other lists (row_1, row_2, row_3, row_4, and row_5). A list that contains other lists is called a list of lists.

The data_set variable is still a list, which means we can retrieve individual list elements and perform list slicing using the syntax we learned. Below, we:

Retrieve the first list element (row_1) using data_set[0].
Retrieve the last list element (row_5) using data_set[-1].
Retrieve the first two list elements (row_1 and row_2) by performing list slicing using data_set[:2].


In [12]:
data_set = [row_1, row_2, row_3, row_4, row_5]

print(data_set[0]) #Retrieve the first list element (row_1) using data_set[0].
print(data_set[-1]) #Retrieve the last list element (row_5) using data_set[-1].
print(data_set[:2]) #Retrieve the first two list elements (row_1 and row_2) by performing list slicing using data_set[:2].

['Facebook', 0.0, 'USD', 2974676, 3.5]
['Pandora - Music & Radio', 0.0, 'USD', 1126879, 4.0]
[['Facebook', 0.0, 'USD', 2974676, 3.5], ['Instagram', 0.0, 'USD', 2161558, 4.5]]


We'll often need to retrieve individual elements from a list that's part of a list of lists — for instance, we may want to retrieve the value 3.5 from ['Facebook', 0.0, 'USD', 2974676, 3.5], which is part of the data_set list of lists. Below, we extract 3.5 from data_set using what we've learned:

* We retrieve row_1 using data_set[0], and assign the result to a variable named fb_row.
* We print fb_row, which outputs ['Facebook', 0.0, 'USD', 2974676, 3.5].
* We retrieve the last element from fb_row using fb_row[-1] (since fb_row is a list), and assign the result to a variable named fb_rating.
* Print fb_rating, which outputs 3.5

In [13]:
print(data_set)

fb_row = data_set[0]
print(fb_row)

fb_rating = fb_row[-1]
print(fb_rating)

[['Facebook', 0.0, 'USD', 2974676, 3.5], ['Instagram', 0.0, 'USD', 2161558, 4.5], ['Clash of Clans', 0.0, 'USD', 2130805, 4.5], ['Temple Run', 0.0, 'USD', 1724546, 4.5], ['Pandora - Music & Radio', 0.0, 'USD', 1126879, 4.0]]
['Facebook', 0.0, 'USD', 2974676, 3.5]
3.5


Above, we retrieved 3.5 in two steps: we first retrieved data_set[0], and then we retrieved fb_row[-1]. However, there's an easier way to retrieve the same value of 3.5 by chaining the two indices ([0] and [-1]) — the code data_set[0][-1] retrieves 3.5:

![alt text](https://s3.amazonaws.com/dq-content/312/py1m2_cb16_new2.svg)

Above, we've seen two ways of retrieving the value 3.5. Both ways lead to the same output (3.5), but the second way involves less typing because it elegantly combines the steps we see in the first case. While you can choose either option, people generally choose the second one.

1. In the code editor, we've already stored the five rows as lists in separate variables. Group together the five lists in a list of lists. Assign the resulting list of lists to a variable named app_data_set.
2. Compute the average rating of the apps by retrieving the right data points from the app_data_set list of lists.
* The rating is the last element of each row. You'll need to sum up the ratings and then divide by the number of ratings.
* Assign the result to a variable named avg_rating.



In [ ]:
app_data_set = [row_1, row_2, row_3, row_4, row_5]
